paths:
  # Glob pattern relative to the repository root for matching files. The path separator is always '/'.
  # This example configures any YAML file under the '.github/workflows/' directory.
  .github/**:
    # List of regular expressions to filter errors by the error messages.
    ignore:
      # - 'shellcheck reported issue in this script: SC2086:.+'
      # - 'the runner of ".+" action is too old to run on GitHub Actions'
      - 'configuration variable name "retention-days" can only contain alphabets, decimal numbers, and.+'
      - 'configuration variable name ".+" can only contain alphabets, decimal numbers, and'
      - 'configuration variable name .+ can only contain alphabets, decimal numbers, and.+'
