name: Release

on:
  push:
    branches:
      - master

jobs:
  release-tag:
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag.yaml@v1
    permissions:
      contents: write
    with:
      branch: ${{ github.ref_name }}

  retagging:
    needs: release-tag
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag-update-latest-major.yaml@v1
    permissions:
      contents: write
    with:
      new_tag: ${{ needs.release-tag.outputs.new_tag }}
