name: Release

on:
  push:
    branches:
      - master

jobs:
  # Merges acc into master and release new tag for the workflow
  merge-into-master:
    uses: guidion-digital/release-workflows/.github/workflows/github-merge-into-master.yaml@release-workflows
    permissions:
      contents: write

  release-module-version:
    needs: [merge-into-master]
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag.yaml@release-workflows
    permissions:
      contents: write
