name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  test-workflow:
    uses: guidion-digital/release-workflows/.github/workflows/github-test-workflow.yaml@ignore-options
    permissions:
      pull-requests: write
    with:
      actionlint_flags: -config-file .github/actionlint.yaml

  test-release-tag:
    needs: test-workflow
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag-dry-run.yaml@v1
    with:
      branch: ${{ github.ref_name }}
