name: Test

on:
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
    branches:
      - master

jobs:
  test-workflow:
    uses: guidion-digital/release-workflows/.github/workflows/github-test-workflow.yaml@ignore-options
    permissions:
      pull-requests: write
      contents: read
    with:
      actionlint_flags: -ignore 'type of expression at ".+ must be number but found type string'
       

  test-release-tag:
    needs: test-workflow
    uses: guidion-digital/release-workflows/.github/workflows/github-release-tag-dry-run.yaml@v1
    with:
      branch: ${{ github.ref_name }}
