on:
  workflow_call:
  
jobs:
    reviewdog-tf-validate:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v4
        - uses: reviewdog/action-terraform-validate@v1
          with:
            reporter: github-pr-review
            terraform_version: 1.6.5
