on:
  workflow_call:

jobs:
  test-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        working-directory: ./examples
        run: echo "matrix=$(ls | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  tests:
    runs-on: ubuntu-latest
    needs: [ test-list ]
    strategy:
      matrix:
        folders: ${{ fromJson(needs.test-list.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
      - name: Install tflocal
        run: pip install terraform-local
      - name: Test API
        working-directory: ./examples
        run: |
          cd "${{ matrix.folders }}"
          tflocal init
          tflocal plan
      - name: Final step # Needed because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
        run: echo Completed