on:
  workflow_call:

jobs:
  get-matrix-directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        working-directory: ./examples
        run: echo "matrix=$(ls | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  localstack-plan:
    needs: get-matrix-directories
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    strategy:
      matrix:
        folders: ${{ fromJson(needs.get-matrix-directories.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            terraform:
              - '**/*.tf'
      - name: Start LocalStack
        if: steps.changes.outputs.terraform == 'true'
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
      - name: Install tflocal
        if: steps.changes.outputs.terraform == 'true'
        run: pip install terraform-local
      - name: Test API
        if: steps.changes.outputs.terraform == 'true'
        working-directory: ./examples
        run: |
          cd "${{ matrix.folders }}"
          tflocal init
          tflocal plan
  completed:
    needs: localstack-plan
    runs-on: ubuntu-latest
    steps:
      - name: Completed # Needed because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
        run: echo "Completed"