on:
  workflow_call:
    inputs:
      workspace:
        description: Name of the TFC workspace we're using
        required: true
        type: string
      approvers:
        description: CSV of people allowed to approve this plan
        required: true
        type: string
      source_dir:
        description: Name of the directory holding the source to be deployed
        required: false
        type: string
        default: dist
    secrets:
      tfc_api_token:
        description: Token used to talk to Terraform Cloud
        required: true

jobs:
  cancel:
    runs-on: ubuntu-latest
    container: ghcr.io/guidionops/terraform-cloud-deployer:0.0.19
    steps:
      - name: cancel
        run: tfcd -t ${{secrets.tfc_api_token}} -w ${{inputs.workspace}} run cancel --auto-approve current

  tf-init:
    needs: cancel
    runs-on: ubuntu-latest
    container: ghcr.io/guidionops/terraform-cloud-deployer:0.0.19
    steps:
      - name: Get the build artifacts and Terraform files
        uses: actions/download-artifact@v4
        with:
          name: build-and-terraform
      - name: init
        run: TF_IN_AUTOMATION=true TF_TOKEN_app_terraform_io=${{secrets.tfc_api_token}} TF_WORKSPACE=${{inputs.workspace}} terraform init
      - name: Upload Terraform files and build
        uses: actions/upload-artifact@v4
        with:
          name: build-and-terraform-full
          path: |
            ${{ inputs.source_dir }}
            *.tf
            .terraform
            .terraform.lock.hcl

  tf-plan:
    needs: tf-init
    runs-on: ubuntu-latest
    container: ghcr.io/guidionops/terraform-cloud-deployer:0.0.19
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Get the build artifacts and Terraform files
        uses: actions/download-artifact@v4
        with:
          name: build-and-terraform-full
      - name: plan
        run: |
          TF_IN_AUTOMATION=true TF_TOKEN_app_terraform_io=${{secrets.tfc_api_token}} TF_WORKSPACE=${{inputs.workspace}} terraform plan
          echo "WARNING: This is a speculative plan. It may not reflect what you see when running terraform apply"
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ inputs.approvers }}

  tf-apply:
    needs: tf-plan
    runs-on: ubuntu-latest
    container: ghcr.io/guidionops/terraform-cloud-deployer:0.0.19
    steps:
      - name: Get the build artifacts and Terraform files
        uses: actions/download-artifact@v4
        with:
          name: build-and-terraform-full
      - name: Run terraform apply with auto-approval
        run: TF_IN_AUTOMATION=true TF_TOKEN_app_terraform_io=${{secrets.tfc_api_token}} TF_WORKSPACE=${{inputs.workspace}} terraform apply -auto-approve
