on:
  workflow_call:
    secrets:
      tfc_planner_api_token:
        description: Token used to retreieve private modules from Terraform Cloud
        required: false
  
jobs:
    reviewdog-tf-validate:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v4
        - uses: reviewdog/action-terraform-validate@v1
          with:
            reporter: github-pr-review
            terraform_version: 1.6.5
          env:
            TF_TOKEN_app_terraform_io: ${{ secrets.tfc_planner_api_token }}
