on:
  workflow_call:
  
jobs:
    reviewdog:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pull-requests: write
      steps:
        - uses: actions/checkout@v4
        - uses: reviewdog/action-terraform-validate@v1
          with:
            reporter: github-pr-review
            fail_on_error: true
        - uses: reviewdog/action-tflint@v1
          with:
            reporter: github-pr-review
            fail_on_error: true
