on:
  workflow_call:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.changes.outputs.terraform }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          terraform:
            - '**/*.tf'

  get-matrix-directories:
    needs: changes
    if: ${{ needs.changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        working-directory: ./examples
        run: echo "matrix=$(ls | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  localstack-plan:
    needs: get-matrix-directories
    if: ${{ needs.changes.outputs.terraform == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    strategy:
      matrix:
        folders: ${{ fromJson(needs.get-matrix-directories.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
      - name: Install tflocal
        run: pip install terraform-local
      - name: Test API
        working-directory: ./examples
        run: |
          cd "${{ matrix.folders }}"
          tflocal init
          tflocal plan

  completed:
    needs: localstack-plan
    # if: ${{ needs.changes.outputs.terraform == 'true' }}
    if: |
      ${{ needs.changes.outputs.terraform == 'true' }} ||
      ${{ needs.changes.outputs.terraform == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Completed # Needed because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
        run: echo "Completed"