on:
  workflow_call:
    secrets:
      tfc_planner_api_token:
        description: Token used to retreieve private modules from Terraform Cloud
        required: false
  
jobs:
  reviewdog-tf-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-and-terraform-full
      - uses: reviewdog/action-terraform-validate@v1
        with:
          reporter: github-pr-review
          terraform_version: 1.6.1
          terraform_cloud_token: ${{ secrets.tfc_planner_api_token }}
