on:
  workflow_call:

jobs:
  terraform-file-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      result: ${{ steps.terraform-file-changes.outputs.terraform }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: terraform-file-changes
      with:
        filters: |
          terraform:
            - '**/*.tf'

  get-matrix-directories:
    needs: terraform-file-changes
    if: ${{ needs.terraform-file-changes.outputs.result == 'true' }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        working-directory: ./examples
        run: echo "matrix=$(find -- * -type d | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  localstack-plan:
    needs: get-matrix-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folders: ${{ fromJson(needs.get-matrix-directories.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.4"
      - name: Install tflocal
        run: pip install terraform-local
      - name: Run Terraform init and plan
        working-directory: ./examples
        run: |
          cd "${{ matrix.folders }}"
          tflocal init
      - name: Test API
        run: tflocal plan

  # Required because matrix tests have dynamic workflow names based on the folder name. This is something we cannot make a required test from.
  # Skipped tests are marked as succesfull in GitHub, we test here if it was a succesfull run and then mark it as such, if it's skipped or fails then it's marked as failed.
  completed:
      if: ${{ !cancelled() }}
      runs-on: ubuntu-latest
      needs: [terraform-file-changes, localstack-plan]
      steps:
        - id: workflow-or-terraform-change
          if: ${{ (needs.terraform-file-changes.outputs.result == 'false')  || (needs.localstack-plan.result  == 'success') }}
          run: exit 0
        - if: failure() || steps.workflow-or-terraform-change.outcome != 'success'
          run: exit 1
